spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/community_db?serverTimezone=UTC
  application:
    name: community

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQysdafasdfasdfasdfasdfasdfa
